### ISSUE TITLE
Allgemein - kaputte Charakterbögen blockieren oft die Bearbeitung

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#106]
Zahlreiche Falschhandhabungen sorgen dafür, dass ein Charakter sehr schnell nicht mehr bearbeitet werden kann.

Vielleicht wären ergänzende try-catch-Blöcke hilfreich, um das Testen zu erleichtern und im catch oder finally auch wertvolle Informationen zu loggen? :)

**Comment by Thegoodmen** [comment]
Leider nicht wirklich umsetzbar - maximal ein Debug Bogen in dem man direkt Dinge rauswerfen und anpassen kann.
