### ISSUE TITLE
Lokalisierung - EN

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#107]
Da die Spielerschaft zu 100% deutsch ist und Foundry Spielern nativ immer die englische Sprache zuweist, hätte ich zwei Lösungsansätze:
1. Beim Login ein Fenster zur Sprachwahl anbieten.
2. Die englische Übersetzung erst einmal mit den deutschen Inhalten befüllen.

**Comment by Thegoodmen** [comment]
Beides für den Moment umgesetzt
