### ISSUE TITLE
Fernkampf gegen NSC-  negative Paradewerte

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#110]
Wenn ich mit einer Fernkampfwaffe einen unwichtigen NSC (Goon) angreife, dann würfelt dieser automatisch ein Ausweichen. Auf dieses sollte korrekterweise ein Malus von -4/-8 je nach Fernkampfwaffenart angewandt werden.

Stattdessen würfeln die NSCs aber nicht auf ihren Paradebasiswert -4/-8, sondern nur auf -4/-8, was inhaltlich falsch ist.

**Comment by Thegoodmen** [comment]
Is fixed
