### ISSUE TITLE
Abzüge durch Behinderung

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#111]
Wenn ein Charakter mehr Behinderung hat, als seine eBE mit der passenden Waffe beträgt, müssen die weiteren Behinderungspunkte abwechselnd von AT und PA (PA zuerst) abgezogen werden und nicht von AT und PA. Das wird inhaltlich falsch gehandhabt.

**Comment by Thegoodmen** [comment]
Fixed
