### ISSUE TITLE
Astrale Regeneration - diverse Fehler?

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#122]
Bei Charakteren mit Meisterlicher Regeneration kommt kein statischer Wert heraus. Dieser unterscheidet sich um mehr als den einen Punkt der IN-Probe.

Besitzt der Charakter zusätzlich den Vorteil Astrale Regeneration, schwankt die Reg noch weiter auseinander.

Nein, es liegt nicht daran, dass der Charakter alle fehlenden AsP regeneriert hat und deshalb weniger registrieren musste.

Beobachtet an: Lumiella und unserer Mirhamer Gildenmagierin sonntags

**Comment by Thegoodmen** [comment]
Grundsätzlich gelöst, offener Punkt siehe verlinktes Ticket:

#131
