### ISSUE TITLE
Kopfwunde - Attributsbehandlung als String

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#123]
Wenn ein Charakter eine wirkende Kopfwunde besitzt, zeigt es im ersten Reiter "16-2" als Wert für Mut an.

Bitte allgemein prüfen, ob hier Stringhandhabung von Zahlen stattfindet.

**Comment by Thegoodmen** [comment]
Sollte jetzt passen
