### ISSUE TITLE
Initaitive würfeln funktioniert meist nicht

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#124]
Gegenwärtig ist es nicht oder nicht immer möglich, die Initiative der Kampfteilnehmer zu würfeln.

Es wird zwar ein Initiativewurf durchgeführt, aber dieser wird nicht in den Combattracker übertragen.

Mehrfaches Würfeln sorgt für weitere Würfe, aber ebenfalls keine Übertragung.

**Comment by Thegoodmen** [comment]
Should be fixed
