### ISSUE TITLE
Combattracker - Manuelles Eintragen der Initiative funktioniert nicht

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#126]
Wenn ich einen Kampfteilnehmer editiere und ihm einen Initiativewert zuweise, dann wird dieser Wert zwar dem Charakter zugewiesen, aber nicht in den Combattracker überführt.

**Comment by Thegoodmen** [comment]
Nicht reproduzierbar
