### ISSUE TITLE
Combattracker - 0.9.0 Start des Kampfes funktioniert nicht

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#127]
"Begin Combat" funktioniert nicht, das kann aber unter Umständen an kaputten Charakteren liegen. Trotzdem sicherheitshalber gesondert reportet, damit du es am Ende schließen kannst <3

**Comment by Thegoodmen** [comment]
Sind die kaputten Chars
