### ISSUE TITLE
Kampfwerte werden teilweise verzehnfacht

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#128]
Manchmal tritt das Problem auf, dass an den Kampfwert eine endständige 0 addiert wird. Also nicht +0, sondern +"0".

Das sorgt für lustige Kampfwerte ... bitte fixen :)

**Comment by Thegoodmen** [comment]
Ohne Konkretes Beispiel nicht behandelbar. Ich hab es vielleicht gefixed... oder auch nicht
