### ISSUE TITLE
Regeneration - Schnelle Heilung wird nicht oder nur eine Stufe erfasst

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#129]
Charakter mit Schneller Heilung III regeneriert Lebenspunkte - Lebenspunkteheilung ist zu gering. Der Wert wirkt erratisch und ist mal Würfelergebnis (+1 für KO) +0/+1/+2/+3. Bitte prüfen und reparieren :)

**Comment by Thegoodmen** [comment]
Fixed in next Update
