### ISSUE TITLE
Kampferstellung -> Initiative würfelt, trägt aber nicht in Combattracker ein

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#137]
![image](https://github.com/user-attachments/assets/c991c329-ee50-448e-9e73-274d919cd37d)
Schritt 0: Actor auf Karte
Schritt 1: Actor in Kampf
Schritt 2: Kampfreiter -> Würfel 
Schritt 3: Initiative wird im Chat gewürfelt
Abweichung:
erwartet: Initiative wird im Tracker dem Charakter zugeordnet
tatsächlich: Charakter hat weiterhin keine Initiative

**Comment by Thegoodmen** [comment]
Will be fixed in the next Release Candidat
