### ISSUE TITLE
Modifier Regeneration

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#45]
Wenn ich als astraler Charakter im Reiter Kampf einen Modifikator angebe, werden meine AsP- und LeP-Regeneration um diesen Wert modifiziert.

Da ich z.B. auch einen Modifikator durch HKW bekommen kann, wäre es gut, diese beiden Modifier zu trennen.

**Comment by Thegoodmen** [comment]
Aufteilung wurde im neusten Update hinzugefügt!
