### ISSUE TITLE
INI-Basis-Berechnung falsch?

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#46]
MU 16, IN 14, GE 14 -> Ini-Basis: 16+16+14+14 -> 60/5 -> 12

Der Bogen zeigt INI-Basis 10, bitte prüfen.

![image](https://github.com/Thegoodmen/Goodys-DSA-4.1-System/assets/66550038/879b19b4-8698-4b38-aa00-89af8a3f7da9)

**Comment by Thegoodmen** [comment]
Sind 12 + Kampfreflexe sind 14.

- 1 vom angelegten Wurfspeer
- 3 von der angelegten Ochsenherde

Hat zur Folge InI Basis 10 

Wenn etwas angelegt ist (im Kampfbogen als Nutzbar angezeigt wird) Beeinflusst es die InI Berechnung.
