### ISSUE TITLE
Fleischer 10, Anatomie 10

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#59]
Fleischer TaW 10 sorgt für 1 Schaden im Kampf gegen Tiere
Anatomie TaW 10 sorgt für 1 Schaden im Kampf gegen Humanoide/Menschen

keine Ahnung, wie du das umsetzen willst ;) Gegner = SC/NPC Bogen oder so?

**Comment by Thegoodmen** [comment]
Im nächsten Update enthalten!
