### ISSUE TITLE
Initiativeboni aus Rasse und Profession

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#60]
Goblins bekommen INI-Boni, Diebe bekommen INI-Boni, beide werden bisher nicht berücksichtigt, denke ich

**Comment by Thegoodmen** [comment]
Ein Feld für den Modi ist für INI vorhanden und kann für den Moment gesetzt werden. 
Automatische Zuweisung bei Profession / Rasse folgt mit Milestone 1.2
