### ISSUE TITLE
Feature Request: weniger raumgreifende 3W20-Proben

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#68]
umstellbar zwischen "wie bisher" und 
Talentname [W1, W2, W3] TaW, Ergebnis: -7 TaP* < als Einzeiler, damit viele Proben auf den Bildschirm passen (z.B. als Systemeinstellung)

**Comment by Thegoodmen** [comment]
Ist im nächsten / 1.0 Release teilweise enthalten. Systemeinstellung ist für den Moment noch nicht geplannt.
