### ISSUE TITLE
Mirakelproben funktionieren nicht

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#94]
![image](https://github.com/Thegoodmen/Goodys-DSA-4.1-System/assets/66550038/74b4309b-e956-445b-83e4-9edef5696fa9)
Versuch eine Praiotin eine Mirakleprobe durchführen zu lassen

**Comment by Thegoodmen** [comment]
Wurde behoben in v0.8.1
