### ISSUE TITLE
Karmalqueste fehlerhaft als ruhend geflaggt

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#95]
![image](https://github.com/Thegoodmen/Goodys-DSA-4.1-System/assets/66550038/306f0779-4077-4b86-8b98-d5253e7b1cf2)

**Comment by yagrima** [comment]
TaW GöKu ist >= 7, LkW ist >= 7
fragst du eventuell zwingend die Ritualkenntnis des Schamanen oder Kontakt zum Großen Geist ab?

**Comment by Thegoodmen** [comment]
Fixed, or did not worked properly
