### ISSUE TITLE
Änderung freie AP ist weiterhin nicht möglich

### ISSUE THREAD

**Issue by yagrima** [Thegoodmen/Goodys-DSA-4.1-System#97]
Prio 99

![image](https://github.com/user-attachments/assets/f4f54b28-bfa4-46ef-8da1-f1514f42d994)

Änderungen im Feld "Freie AP" werden nach erneutem Öffnen des Bogens zurückgesetzt

**Comment by Thegoodmen** [comment]
Felder von Contenteditable auf Input Fields gewechselt. Problem damit behoben.
